# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildno: '100'

steps:
# - task: Docker@2
#   inputs:
#     containerRegistry: 'Docker Hub'
#     repository: 'tudordumitriu/azweb'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $(Build.BuildNumber).replace('.', '') | Set-Content $(buildno)
      az extension add --name azure-devops
      echo $(System.AccessToken) | az devops login
      az devops configure -d organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
      Write-Host 'Before update:' + '$(System.TeamFoundationCollectionUri)'  + ':' + '$(buildno)'   
      az pipelines variable-group variable update --id 1 --name webbuildno --value $(buildno)
