# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'tudordumitriu/azweb'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      az extension add --name azure-devops
      Write-Host $(System.AccessToken)
      echo $(System.AccessToken) | az devops login
      az devops configure -d organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
      Write-Host 'Before update:' + '$(System.TeamFoundationCollectionUri)'  + ':' + '$(Build.BuildId)'   
      az pipelines variable-group variable update --id 1 --name webbuildno --value $(Build.BuildNumber)
