apiVersion: apps/v1
kind: Deployment
metadata:
  name: azweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azweb
  template:
    metadata:
      labels:
        app: azweb
    spec:
      containers:
      - name: azweb
        image: tudordumitriu/azweb:{version}
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name : azweb  
spec:
  selector:
    app: azweb
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
    nodePort: 30666
  type: NodePort
